/*
 * generated by Xtext
 */
package org.eclipse.amalgam.tutorials.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DroidRuntimeModule extends org.eclipse.amalgam.tutorials.xtext.AbstractDroidRuntimeModule {

}
