/*
 * generated by Xtext
 */
package org.eclipse.amalgam.tutorials.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DroidUiModule extends org.eclipse.amalgam.tutorials.xtext.ui.AbstractDroidUiModule {
	public DroidUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
