/*
 * generated by Xtext
 */
package org.eclipse.amalgam.tutorials.xtext.scoping;

import org.eclipse.amalgam.tutorials.xtext.droid.*;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;


/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class DroidScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_LayoutParams_layout_below(LayoutParams lp, EReference ref){
		View containingView = ((View) lp.eContainer() );
		ViewCollection containingCollection = ((ViewCollection) containingView.eContainer() );
		return Scopes.scopeFor(containingCollection.getViews());
	}


	//????
	public IScope scope_LayoutParams_layout_below(View view, EReference ref){
		ViewCollection containingCollection = ((ViewCollection) view.eContainer() );
		return Scopes.scopeFor(containingCollection.getViews());
	}

}
