/*
 * generated by Xtext
 */
package org.eclipse.amalgam.tutorials.xtext.scoping;

import org.eclipse.amalgam.tutorials.xtext.droid.LayoutParams;
import org.eclipse.amalgam.tutorials.xtext.droid.View;
import org.eclipse.amalgam.tutorials.xtext.droid.ViewCollection;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;


/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class DroidScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_LayoutParams_below(LayoutParams lp, EReference ref){
		//Only the siblings of the containing View
		View containingView = ((View) lp.eContainingFeature().eContainer() );
		ViewCollection containingCollection = ((ViewCollection) containingView.eContainingFeature().eContainer() );
		return Scopes.scopeFor(containingCollection.getViews());
	}
}
