<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="droid"
    nsURI="http://www.eclipse.org/amalgam/tutorials/xtext/Droid" nsPrefix="droid">
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" eType="#//ManifestFile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1"
        eType="#//Layout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManifestFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValueResource" eSuperTypes="#//ValueResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValueResource" eSuperTypes="#//ValueResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValueResource" eSuperTypes="#//ValueResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorValueResource" eSuperTypes="#//ValueResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionValueResource" eSuperTypes="#//ValueResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//DimensionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableResource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="BitmapDrawableResource" eSuperTypes="#//DrawableResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionDrawableResource" eSuperTypes="#//DrawableResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//DrawableResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//DrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnimationResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
        eType="#//Widget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="top" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//DrawableResourcePropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickable" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadeScrollBars" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isScrollContainer" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericWidget" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextView" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageButton" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//DrawableImageResourcePropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spinner" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prompt" eType="#//StringPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditText" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editable" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numeric" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="password" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phoneNumber" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemLayout" eType="#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabs" upperBound="-1" eType="#//Tab"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tab">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoToURLAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShowLayoutAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeActivityAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadResourceAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterLoad" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//StringValueResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//IntegerValueResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//BooleanValueResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//ColorValueResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//DimensionValueResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableResourcePropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//DrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableImageResourcePropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//DrawableResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DimensionKind">
    <eLiterals name="dp" literal="dp"/>
    <eLiterals name="sp" value="1" literal="sp"/>
    <eLiterals name="pt" value="2" literal="pt"/>
    <eLiterals name="px" value="3" literal="px"/>
    <eLiterals name="mm" value="4" literal="mm"/>
    <eLiterals name="in" value="5" literal="in"/>
  </eClassifiers>
</ecore:EPackage>
