/*
* generated by Xtext
*/
package org.eclipse.amalgam.tutorials.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.amalgam.tutorials.xtext.services.DroidGrammarAccess;

public class DroidParser extends AbstractContentAssistParser {
	
	@Inject
	private DroidGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.amalgam.tutorials.xtext.ui.contentassist.antlr.internal.InternalDroidParser createParser() {
		org.eclipse.amalgam.tutorials.xtext.ui.contentassist.antlr.internal.InternalDroidParser result = new org.eclipse.amalgam.tutorials.xtext.ui.contentassist.antlr.internal.InternalDroidParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getApplicationAccess().getAlternatives_5(), "rule__Application__Alternatives_5");
					put(grammarAccess.getResourceAccess().getAlternatives(), "rule__Resource__Alternatives");
					put(grammarAccess.getValueResourceAccess().getAlternatives(), "rule__ValueResource__Alternatives");
					put(grammarAccess.getDrawableResourceAccess().getAlternatives(), "rule__DrawableResource__Alternatives");
					put(grammarAccess.getWidgetAccess().getAlternatives(), "rule__Widget__Alternatives");
					put(grammarAccess.getActivityAccess().getAlternatives(), "rule__Activity__Alternatives");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getPropertyValueAccess().getAlternatives(), "rule__PropertyValue__Alternatives");
					put(grammarAccess.getStringPropertyValueAccess().getAlternatives(), "rule__StringPropertyValue__Alternatives");
					put(grammarAccess.getStringPropertyValueAccess().getAlternatives_1(), "rule__StringPropertyValue__Alternatives_1");
					put(grammarAccess.getIntegerPropertyValueAccess().getAlternatives(), "rule__IntegerPropertyValue__Alternatives");
					put(grammarAccess.getIntegerPropertyValueAccess().getAlternatives_1(), "rule__IntegerPropertyValue__Alternatives_1");
					put(grammarAccess.getBooleanPropertyValueAccess().getAlternatives(), "rule__BooleanPropertyValue__Alternatives");
					put(grammarAccess.getBooleanPropertyValueAccess().getAlternatives_1(), "rule__BooleanPropertyValue__Alternatives_1");
					put(grammarAccess.getColorPropertyValueAccess().getAlternatives(), "rule__ColorPropertyValue__Alternatives");
					put(grammarAccess.getColorPropertyValueAccess().getAlternatives_1(), "rule__ColorPropertyValue__Alternatives_1");
					put(grammarAccess.getDimensionPropertyValueAccess().getAlternatives(), "rule__DimensionPropertyValue__Alternatives");
					put(grammarAccess.getDimensionPropertyValueAccess().getAlternatives_1(), "rule__DimensionPropertyValue__Alternatives_1");
					put(grammarAccess.getDrawableResourcePropertyValueAccess().getAlternatives(), "rule__DrawableResourcePropertyValue__Alternatives");
					put(grammarAccess.getDrawableResourcePropertyValueAccess().getAlternatives_1(), "rule__DrawableResourcePropertyValue__Alternatives_1");
					put(grammarAccess.getDrawableImageResourcePropertyValueAccess().getAlternatives(), "rule__DrawableImageResourcePropertyValue__Alternatives");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getDimensionKindAccess().getAlternatives(), "rule__DimensionKind__Alternatives");
					put(grammarAccess.getApplicationAccess().getGroup(), "rule__Application__Group__0");
					put(grammarAccess.getManifestFileAccess().getGroup(), "rule__ManifestFile__Group__0");
					put(grammarAccess.getGenericResourceAccess().getGroup(), "rule__GenericResource__Group__0");
					put(grammarAccess.getMenuResourceAccess().getGroup(), "rule__MenuResource__Group__0");
					put(grammarAccess.getStringValueResourceAccess().getGroup(), "rule__StringValueResource__Group__0");
					put(grammarAccess.getIntegerValueResourceAccess().getGroup(), "rule__IntegerValueResource__Group__0");
					put(grammarAccess.getBooleanValueResourceAccess().getGroup(), "rule__BooleanValueResource__Group__0");
					put(grammarAccess.getColorValueResourceAccess().getGroup(), "rule__ColorValueResource__Group__0");
					put(grammarAccess.getDimensionValueResourceAccess().getGroup(), "rule__DimensionValueResource__Group__0");
					put(grammarAccess.getBitmapDrawableResourceAccess().getGroup(), "rule__BitmapDrawableResource__Group__0");
					put(grammarAccess.getTransitionDrawableResourceAccess().getGroup(), "rule__TransitionDrawableResource__Group__0");
					put(grammarAccess.getAnimationResourceAccess().getGroup(), "rule__AnimationResource__Group__0");
					put(grammarAccess.getLayoutAccess().getGroup(), "rule__Layout__Group__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup(), "rule__GenericWidget__Group__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_2(), "rule__GenericWidget__Group_2__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_0(), "rule__GenericWidget__Group_4_0__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_1(), "rule__GenericWidget__Group_4_1__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_2(), "rule__GenericWidget__Group_4_2__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_3(), "rule__GenericWidget__Group_4_3__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_4(), "rule__GenericWidget__Group_4_4__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_5(), "rule__GenericWidget__Group_4_5__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_6(), "rule__GenericWidget__Group_4_6__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_4_7(), "rule__GenericWidget__Group_4_7__0");
					put(grammarAccess.getGenericWidgetAccess().getGroup_5(), "rule__GenericWidget__Group_5__0");
					put(grammarAccess.getTextViewAccess().getGroup(), "rule__TextView__Group__0");
					put(grammarAccess.getTextViewAccess().getGroup_2(), "rule__TextView__Group_2__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_0(), "rule__TextView__Group_4_0__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_1(), "rule__TextView__Group_4_1__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_2(), "rule__TextView__Group_4_2__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_3(), "rule__TextView__Group_4_3__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_4(), "rule__TextView__Group_4_4__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_5(), "rule__TextView__Group_4_5__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_6(), "rule__TextView__Group_4_6__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_7(), "rule__TextView__Group_4_7__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_8(), "rule__TextView__Group_4_8__0");
					put(grammarAccess.getTextViewAccess().getGroup_4_9(), "rule__TextView__Group_4_9__0");
					put(grammarAccess.getTextViewAccess().getGroup_5(), "rule__TextView__Group_5__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getButtonAccess().getGroup_2(), "rule__Button__Group_2__0");
					put(grammarAccess.getButtonAccess().getGroup_4_0(), "rule__Button__Group_4_0__0");
					put(grammarAccess.getButtonAccess().getGroup_4_1(), "rule__Button__Group_4_1__0");
					put(grammarAccess.getButtonAccess().getGroup_4_2(), "rule__Button__Group_4_2__0");
					put(grammarAccess.getButtonAccess().getGroup_4_3(), "rule__Button__Group_4_3__0");
					put(grammarAccess.getButtonAccess().getGroup_4_4(), "rule__Button__Group_4_4__0");
					put(grammarAccess.getButtonAccess().getGroup_4_5(), "rule__Button__Group_4_5__0");
					put(grammarAccess.getButtonAccess().getGroup_4_6(), "rule__Button__Group_4_6__0");
					put(grammarAccess.getButtonAccess().getGroup_4_7(), "rule__Button__Group_4_7__0");
					put(grammarAccess.getButtonAccess().getGroup_4_8(), "rule__Button__Group_4_8__0");
					put(grammarAccess.getButtonAccess().getGroup_4_9(), "rule__Button__Group_4_9__0");
					put(grammarAccess.getButtonAccess().getGroup_5(), "rule__Button__Group_5__0");
					put(grammarAccess.getImageButtonAccess().getGroup(), "rule__ImageButton__Group__0");
					put(grammarAccess.getImageButtonAccess().getGroup_2(), "rule__ImageButton__Group_2__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_0(), "rule__ImageButton__Group_4_0__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_1(), "rule__ImageButton__Group_4_1__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_2(), "rule__ImageButton__Group_4_2__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_3(), "rule__ImageButton__Group_4_3__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_4(), "rule__ImageButton__Group_4_4__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_5(), "rule__ImageButton__Group_4_5__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_6(), "rule__ImageButton__Group_4_6__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_7(), "rule__ImageButton__Group_4_7__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_8(), "rule__ImageButton__Group_4_8__0");
					put(grammarAccess.getImageButtonAccess().getGroup_4_9(), "rule__ImageButton__Group_4_9__0");
					put(grammarAccess.getImageButtonAccess().getGroup_5(), "rule__ImageButton__Group_5__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_2(), "rule__Link__Group_2__0");
					put(grammarAccess.getLinkAccess().getGroup_4_0(), "rule__Link__Group_4_0__0");
					put(grammarAccess.getLinkAccess().getGroup_4_1(), "rule__Link__Group_4_1__0");
					put(grammarAccess.getLinkAccess().getGroup_4_2(), "rule__Link__Group_4_2__0");
					put(grammarAccess.getLinkAccess().getGroup_4_3(), "rule__Link__Group_4_3__0");
					put(grammarAccess.getLinkAccess().getGroup_4_4(), "rule__Link__Group_4_4__0");
					put(grammarAccess.getLinkAccess().getGroup_4_5(), "rule__Link__Group_4_5__0");
					put(grammarAccess.getLinkAccess().getGroup_4_6(), "rule__Link__Group_4_6__0");
					put(grammarAccess.getLinkAccess().getGroup_4_7(), "rule__Link__Group_4_7__0");
					put(grammarAccess.getLinkAccess().getGroup_4_8(), "rule__Link__Group_4_8__0");
					put(grammarAccess.getLinkAccess().getGroup_4_9(), "rule__Link__Group_4_9__0");
					put(grammarAccess.getLinkAccess().getGroup_7(), "rule__Link__Group_7__0");
					put(grammarAccess.getSpinnerAccess().getGroup(), "rule__Spinner__Group__0");
					put(grammarAccess.getSpinnerAccess().getGroup_2(), "rule__Spinner__Group_2__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_0(), "rule__Spinner__Group_3_0__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_1(), "rule__Spinner__Group_3_1__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_2(), "rule__Spinner__Group_3_2__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_3(), "rule__Spinner__Group_3_3__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_4(), "rule__Spinner__Group_3_4__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_5(), "rule__Spinner__Group_3_5__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_6(), "rule__Spinner__Group_3_6__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_7(), "rule__Spinner__Group_3_7__0");
					put(grammarAccess.getSpinnerAccess().getGroup_3_8(), "rule__Spinner__Group_3_8__0");
					put(grammarAccess.getEditTextAccess().getGroup(), "rule__EditText__Group__0");
					put(grammarAccess.getEditTextAccess().getGroup_2(), "rule__EditText__Group_2__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_0(), "rule__EditText__Group_4_0__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_1(), "rule__EditText__Group_4_1__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_2(), "rule__EditText__Group_4_2__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_3(), "rule__EditText__Group_4_3__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_4(), "rule__EditText__Group_4_4__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_5(), "rule__EditText__Group_4_5__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_6(), "rule__EditText__Group_4_6__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_7(), "rule__EditText__Group_4_7__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_8(), "rule__EditText__Group_4_8__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_9(), "rule__EditText__Group_4_9__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_10(), "rule__EditText__Group_4_10__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_11(), "rule__EditText__Group_4_11__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_12(), "rule__EditText__Group_4_12__0");
					put(grammarAccess.getEditTextAccess().getGroup_4_13(), "rule__EditText__Group_4_13__0");
					put(grammarAccess.getGenericActivityAccess().getGroup(), "rule__GenericActivity__Group__0");
					put(grammarAccess.getListActivityAccess().getGroup(), "rule__ListActivity__Group__0");
					put(grammarAccess.getListActivityAccess().getGroup_5(), "rule__ListActivity__Group_5__0");
					put(grammarAccess.getTabActivityAccess().getGroup(), "rule__TabActivity__Group__0");
					put(grammarAccess.getTabAccess().getGroup(), "rule__Tab__Group__0");
					put(grammarAccess.getGenericActionAccess().getGroup(), "rule__GenericAction__Group__0");
					put(grammarAccess.getGoToURLActionAccess().getGroup(), "rule__GoToURLAction__Group__0");
					put(grammarAccess.getShowLayoutActionAccess().getGroup(), "rule__ShowLayoutAction__Group__0");
					put(grammarAccess.getInvokeActivityActionAccess().getGroup(), "rule__InvokeActivityAction__Group__0");
					put(grammarAccess.getLoadResourceActionAccess().getGroup(), "rule__LoadResourceAction__Group__0");
					put(grammarAccess.getLoadResourceActionAccess().getGroup_2(), "rule__LoadResourceAction__Group_2__0");
					put(grammarAccess.getLoadResourceActionAccess().getGroup_3(), "rule__LoadResourceAction__Group_3__0");
					put(grammarAccess.getStringPropertyValueAccess().getGroup_1_1(), "rule__StringPropertyValue__Group_1_1__0");
					put(grammarAccess.getIntegerPropertyValueAccess().getGroup_1_1(), "rule__IntegerPropertyValue__Group_1_1__0");
					put(grammarAccess.getBooleanPropertyValueAccess().getGroup_1_1(), "rule__BooleanPropertyValue__Group_1_1__0");
					put(grammarAccess.getColorPropertyValueAccess().getGroup_1_1(), "rule__ColorPropertyValue__Group_1_1__0");
					put(grammarAccess.getDimensionPropertyValueAccess().getGroup_1_1(), "rule__DimensionPropertyValue__Group_1_1__0");
					put(grammarAccess.getDrawableResourcePropertyValueAccess().getGroup_1_1(), "rule__DrawableResourcePropertyValue__Group_1_1__0");
					put(grammarAccess.getDrawableImageResourcePropertyValueAccess().getGroup_1(), "rule__DrawableImageResourcePropertyValue__Group_1__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getFLOATAccess().getGroup(), "rule__FLOAT__Group__0");
					put(grammarAccess.getFLOATAccess().getGroup_1(), "rule__FLOAT__Group_1__0");
					put(grammarAccess.getURLAccess().getGroup(), "rule__URL__Group__0");
					put(grammarAccess.getURLAccess().getGroup_3(), "rule__URL__Group_3__0");
					put(grammarAccess.getURLAccess().getGroup_3_1(), "rule__URL__Group_3_1__0");
					put(grammarAccess.getApplicationAccess().getNameAssignment_1(), "rule__Application__NameAssignment_1");
					put(grammarAccess.getApplicationAccess().getPackageAssignment_2(), "rule__Application__PackageAssignment_2");
					put(grammarAccess.getApplicationAccess().getManifestAssignment_4(), "rule__Application__ManifestAssignment_4");
					put(grammarAccess.getApplicationAccess().getResourcesAssignment_5_0(), "rule__Application__ResourcesAssignment_5_0");
					put(grammarAccess.getApplicationAccess().getLayoutsAssignment_5_1(), "rule__Application__LayoutsAssignment_5_1");
					put(grammarAccess.getApplicationAccess().getActivitiesAssignment_5_2(), "rule__Application__ActivitiesAssignment_5_2");
					put(grammarAccess.getGenericResourceAccess().getNameAssignment_2(), "rule__GenericResource__NameAssignment_2");
					put(grammarAccess.getMenuResourceAccess().getNameAssignment_2(), "rule__MenuResource__NameAssignment_2");
					put(grammarAccess.getStringValueResourceAccess().getNameAssignment_1(), "rule__StringValueResource__NameAssignment_1");
					put(grammarAccess.getStringValueResourceAccess().getValueAssignment_3(), "rule__StringValueResource__ValueAssignment_3");
					put(grammarAccess.getIntegerValueResourceAccess().getNameAssignment_1(), "rule__IntegerValueResource__NameAssignment_1");
					put(grammarAccess.getIntegerValueResourceAccess().getValueAssignment_3(), "rule__IntegerValueResource__ValueAssignment_3");
					put(grammarAccess.getBooleanValueResourceAccess().getNameAssignment_1(), "rule__BooleanValueResource__NameAssignment_1");
					put(grammarAccess.getBooleanValueResourceAccess().getValueAssignment_3(), "rule__BooleanValueResource__ValueAssignment_3");
					put(grammarAccess.getColorValueResourceAccess().getNameAssignment_1(), "rule__ColorValueResource__NameAssignment_1");
					put(grammarAccess.getColorValueResourceAccess().getValueAssignment_3(), "rule__ColorValueResource__ValueAssignment_3");
					put(grammarAccess.getDimensionValueResourceAccess().getNameAssignment_1(), "rule__DimensionValueResource__NameAssignment_1");
					put(grammarAccess.getDimensionValueResourceAccess().getValueAssignment_3(), "rule__DimensionValueResource__ValueAssignment_3");
					put(grammarAccess.getDimensionValueResourceAccess().getUnitAssignment_4(), "rule__DimensionValueResource__UnitAssignment_4");
					put(grammarAccess.getBitmapDrawableResourceAccess().getNameAssignment_1(), "rule__BitmapDrawableResource__NameAssignment_1");
					put(grammarAccess.getBitmapDrawableResourceAccess().getFilenameAssignment_3(), "rule__BitmapDrawableResource__FilenameAssignment_3");
					put(grammarAccess.getTransitionDrawableResourceAccess().getFromAssignment_1(), "rule__TransitionDrawableResource__FromAssignment_1");
					put(grammarAccess.getTransitionDrawableResourceAccess().getToAssignment_3(), "rule__TransitionDrawableResource__ToAssignment_3");
					put(grammarAccess.getAnimationResourceAccess().getNameAssignment_2(), "rule__AnimationResource__NameAssignment_2");
					put(grammarAccess.getLayoutAccess().getNameAssignment_2(), "rule__Layout__NameAssignment_2");
					put(grammarAccess.getLayoutAccess().getWidgetsAssignment_4(), "rule__Layout__WidgetsAssignment_4");
					put(grammarAccess.getGenericWidgetAccess().getIdAssignment_2_1(), "rule__GenericWidget__IdAssignment_2_1");
					put(grammarAccess.getGenericWidgetAccess().getNameAssignment_3(), "rule__GenericWidget__NameAssignment_3");
					put(grammarAccess.getGenericWidgetAccess().getTopAssignment_4_0_1(), "rule__GenericWidget__TopAssignment_4_0_1");
					put(grammarAccess.getGenericWidgetAccess().getLeftAssignment_4_1_1(), "rule__GenericWidget__LeftAssignment_4_1_1");
					put(grammarAccess.getGenericWidgetAccess().getWidthAssignment_4_2_1(), "rule__GenericWidget__WidthAssignment_4_2_1");
					put(grammarAccess.getGenericWidgetAccess().getHeightAssignment_4_3_1(), "rule__GenericWidget__HeightAssignment_4_3_1");
					put(grammarAccess.getGenericWidgetAccess().getBackgroundAssignment_4_4_1(), "rule__GenericWidget__BackgroundAssignment_4_4_1");
					put(grammarAccess.getGenericWidgetAccess().getClickableAssignment_4_5_1(), "rule__GenericWidget__ClickableAssignment_4_5_1");
					put(grammarAccess.getGenericWidgetAccess().getFadeScrollBarsAssignment_4_6_1(), "rule__GenericWidget__FadeScrollBarsAssignment_4_6_1");
					put(grammarAccess.getGenericWidgetAccess().getIsScrollContainerAssignment_4_7_1(), "rule__GenericWidget__IsScrollContainerAssignment_4_7_1");
					put(grammarAccess.getGenericWidgetAccess().getActionsAssignment_5_1(), "rule__GenericWidget__ActionsAssignment_5_1");
					put(grammarAccess.getTextViewAccess().getIdAssignment_2_1(), "rule__TextView__IdAssignment_2_1");
					put(grammarAccess.getTextViewAccess().getTextAssignment_3(), "rule__TextView__TextAssignment_3");
					put(grammarAccess.getTextViewAccess().getTopAssignment_4_0_1(), "rule__TextView__TopAssignment_4_0_1");
					put(grammarAccess.getTextViewAccess().getLeftAssignment_4_1_1(), "rule__TextView__LeftAssignment_4_1_1");
					put(grammarAccess.getTextViewAccess().getWidthAssignment_4_2_1(), "rule__TextView__WidthAssignment_4_2_1");
					put(grammarAccess.getTextViewAccess().getHeightAssignment_4_3_1(), "rule__TextView__HeightAssignment_4_3_1");
					put(grammarAccess.getTextViewAccess().getBackgroundAssignment_4_4_1(), "rule__TextView__BackgroundAssignment_4_4_1");
					put(grammarAccess.getTextViewAccess().getClickableAssignment_4_5_1(), "rule__TextView__ClickableAssignment_4_5_1");
					put(grammarAccess.getTextViewAccess().getFadeScrollBarsAssignment_4_6_1(), "rule__TextView__FadeScrollBarsAssignment_4_6_1");
					put(grammarAccess.getTextViewAccess().getIsScrollContainerAssignment_4_7_1(), "rule__TextView__IsScrollContainerAssignment_4_7_1");
					put(grammarAccess.getTextViewAccess().getHintAssignment_4_8_1(), "rule__TextView__HintAssignment_4_8_1");
					put(grammarAccess.getTextViewAccess().getTextColorAssignment_4_9_1(), "rule__TextView__TextColorAssignment_4_9_1");
					put(grammarAccess.getTextViewAccess().getActionsAssignment_5_1(), "rule__TextView__ActionsAssignment_5_1");
					put(grammarAccess.getButtonAccess().getIdAssignment_2_1(), "rule__Button__IdAssignment_2_1");
					put(grammarAccess.getButtonAccess().getTextAssignment_3(), "rule__Button__TextAssignment_3");
					put(grammarAccess.getButtonAccess().getTopAssignment_4_0_1(), "rule__Button__TopAssignment_4_0_1");
					put(grammarAccess.getButtonAccess().getLeftAssignment_4_1_1(), "rule__Button__LeftAssignment_4_1_1");
					put(grammarAccess.getButtonAccess().getWidthAssignment_4_2_1(), "rule__Button__WidthAssignment_4_2_1");
					put(grammarAccess.getButtonAccess().getHeightAssignment_4_3_1(), "rule__Button__HeightAssignment_4_3_1");
					put(grammarAccess.getButtonAccess().getBackgroundAssignment_4_4_1(), "rule__Button__BackgroundAssignment_4_4_1");
					put(grammarAccess.getButtonAccess().getClickableAssignment_4_5_1(), "rule__Button__ClickableAssignment_4_5_1");
					put(grammarAccess.getButtonAccess().getFadeScrollBarsAssignment_4_6_1(), "rule__Button__FadeScrollBarsAssignment_4_6_1");
					put(grammarAccess.getButtonAccess().getIsScrollContainerAssignment_4_7_1(), "rule__Button__IsScrollContainerAssignment_4_7_1");
					put(grammarAccess.getButtonAccess().getHintAssignment_4_8_1(), "rule__Button__HintAssignment_4_8_1");
					put(grammarAccess.getButtonAccess().getTextColorAssignment_4_9_1(), "rule__Button__TextColorAssignment_4_9_1");
					put(grammarAccess.getButtonAccess().getActionsAssignment_5_1(), "rule__Button__ActionsAssignment_5_1");
					put(grammarAccess.getImageButtonAccess().getIdAssignment_2_1(), "rule__ImageButton__IdAssignment_2_1");
					put(grammarAccess.getImageButtonAccess().getSrcAssignment_3(), "rule__ImageButton__SrcAssignment_3");
					put(grammarAccess.getImageButtonAccess().getTopAssignment_4_0_1(), "rule__ImageButton__TopAssignment_4_0_1");
					put(grammarAccess.getImageButtonAccess().getLeftAssignment_4_1_1(), "rule__ImageButton__LeftAssignment_4_1_1");
					put(grammarAccess.getImageButtonAccess().getWidthAssignment_4_2_1(), "rule__ImageButton__WidthAssignment_4_2_1");
					put(grammarAccess.getImageButtonAccess().getHeightAssignment_4_3_1(), "rule__ImageButton__HeightAssignment_4_3_1");
					put(grammarAccess.getImageButtonAccess().getBackgroundAssignment_4_4_1(), "rule__ImageButton__BackgroundAssignment_4_4_1");
					put(grammarAccess.getImageButtonAccess().getClickableAssignment_4_5_1(), "rule__ImageButton__ClickableAssignment_4_5_1");
					put(grammarAccess.getImageButtonAccess().getFadeScrollBarsAssignment_4_6_1(), "rule__ImageButton__FadeScrollBarsAssignment_4_6_1");
					put(grammarAccess.getImageButtonAccess().getIsScrollContainerAssignment_4_7_1(), "rule__ImageButton__IsScrollContainerAssignment_4_7_1");
					put(grammarAccess.getImageButtonAccess().getHintAssignment_4_8_1(), "rule__ImageButton__HintAssignment_4_8_1");
					put(grammarAccess.getImageButtonAccess().getTextColorAssignment_4_9_1(), "rule__ImageButton__TextColorAssignment_4_9_1");
					put(grammarAccess.getImageButtonAccess().getActionsAssignment_5_1(), "rule__ImageButton__ActionsAssignment_5_1");
					put(grammarAccess.getLinkAccess().getIdAssignment_2_1(), "rule__Link__IdAssignment_2_1");
					put(grammarAccess.getLinkAccess().getTextAssignment_3(), "rule__Link__TextAssignment_3");
					put(grammarAccess.getLinkAccess().getTopAssignment_4_0_1(), "rule__Link__TopAssignment_4_0_1");
					put(grammarAccess.getLinkAccess().getLeftAssignment_4_1_1(), "rule__Link__LeftAssignment_4_1_1");
					put(grammarAccess.getLinkAccess().getWidthAssignment_4_2_1(), "rule__Link__WidthAssignment_4_2_1");
					put(grammarAccess.getLinkAccess().getHeightAssignment_4_3_1(), "rule__Link__HeightAssignment_4_3_1");
					put(grammarAccess.getLinkAccess().getBackgroundAssignment_4_4_1(), "rule__Link__BackgroundAssignment_4_4_1");
					put(grammarAccess.getLinkAccess().getClickableAssignment_4_5_1(), "rule__Link__ClickableAssignment_4_5_1");
					put(grammarAccess.getLinkAccess().getFadeScrollBarsAssignment_4_6_1(), "rule__Link__FadeScrollBarsAssignment_4_6_1");
					put(grammarAccess.getLinkAccess().getIsScrollContainerAssignment_4_7_1(), "rule__Link__IsScrollContainerAssignment_4_7_1");
					put(grammarAccess.getLinkAccess().getHintAssignment_4_8_1(), "rule__Link__HintAssignment_4_8_1");
					put(grammarAccess.getLinkAccess().getTextColorAssignment_4_9_1(), "rule__Link__TextColorAssignment_4_9_1");
					put(grammarAccess.getLinkAccess().getTargetAssignment_6(), "rule__Link__TargetAssignment_6");
					put(grammarAccess.getLinkAccess().getActionsAssignment_7_1(), "rule__Link__ActionsAssignment_7_1");
					put(grammarAccess.getSpinnerAccess().getIdAssignment_2_1(), "rule__Spinner__IdAssignment_2_1");
					put(grammarAccess.getSpinnerAccess().getTopAssignment_3_0_1(), "rule__Spinner__TopAssignment_3_0_1");
					put(grammarAccess.getSpinnerAccess().getLeftAssignment_3_1_1(), "rule__Spinner__LeftAssignment_3_1_1");
					put(grammarAccess.getSpinnerAccess().getWidthAssignment_3_2_1(), "rule__Spinner__WidthAssignment_3_2_1");
					put(grammarAccess.getSpinnerAccess().getHeightAssignment_3_3_1(), "rule__Spinner__HeightAssignment_3_3_1");
					put(grammarAccess.getSpinnerAccess().getBackgroundAssignment_3_4_1(), "rule__Spinner__BackgroundAssignment_3_4_1");
					put(grammarAccess.getSpinnerAccess().getClickableAssignment_3_5_1(), "rule__Spinner__ClickableAssignment_3_5_1");
					put(grammarAccess.getSpinnerAccess().getFadeScrollBarsAssignment_3_6_1(), "rule__Spinner__FadeScrollBarsAssignment_3_6_1");
					put(grammarAccess.getSpinnerAccess().getIsScrollContainerAssignment_3_7_1(), "rule__Spinner__IsScrollContainerAssignment_3_7_1");
					put(grammarAccess.getSpinnerAccess().getPromptAssignment_3_8_1(), "rule__Spinner__PromptAssignment_3_8_1");
					put(grammarAccess.getEditTextAccess().getIdAssignment_2_1(), "rule__EditText__IdAssignment_2_1");
					put(grammarAccess.getEditTextAccess().getTextAssignment_3(), "rule__EditText__TextAssignment_3");
					put(grammarAccess.getEditTextAccess().getTopAssignment_4_0_1(), "rule__EditText__TopAssignment_4_0_1");
					put(grammarAccess.getEditTextAccess().getLeftAssignment_4_1_1(), "rule__EditText__LeftAssignment_4_1_1");
					put(grammarAccess.getEditTextAccess().getWidthAssignment_4_2_1(), "rule__EditText__WidthAssignment_4_2_1");
					put(grammarAccess.getEditTextAccess().getHeightAssignment_4_3_1(), "rule__EditText__HeightAssignment_4_3_1");
					put(grammarAccess.getEditTextAccess().getBackgroundAssignment_4_4_1(), "rule__EditText__BackgroundAssignment_4_4_1");
					put(grammarAccess.getEditTextAccess().getClickableAssignment_4_5_1(), "rule__EditText__ClickableAssignment_4_5_1");
					put(grammarAccess.getEditTextAccess().getFadeScrollBarsAssignment_4_6_1(), "rule__EditText__FadeScrollBarsAssignment_4_6_1");
					put(grammarAccess.getEditTextAccess().getIsScrollContainerAssignment_4_7_1(), "rule__EditText__IsScrollContainerAssignment_4_7_1");
					put(grammarAccess.getEditTextAccess().getHintAssignment_4_8_1(), "rule__EditText__HintAssignment_4_8_1");
					put(grammarAccess.getEditTextAccess().getTextColorAssignment_4_9_1(), "rule__EditText__TextColorAssignment_4_9_1");
					put(grammarAccess.getEditTextAccess().getEditableAssignment_4_10_1(), "rule__EditText__EditableAssignment_4_10_1");
					put(grammarAccess.getEditTextAccess().getNumericAssignment_4_11_1(), "rule__EditText__NumericAssignment_4_11_1");
					put(grammarAccess.getEditTextAccess().getPasswordAssignment_4_12_1(), "rule__EditText__PasswordAssignment_4_12_1");
					put(grammarAccess.getEditTextAccess().getPhoneNumberAssignment_4_13_1(), "rule__EditText__PhoneNumberAssignment_4_13_1");
					put(grammarAccess.getGenericActivityAccess().getNameAssignment_1(), "rule__GenericActivity__NameAssignment_1");
					put(grammarAccess.getGenericActivityAccess().getActionsAssignment_3(), "rule__GenericActivity__ActionsAssignment_3");
					put(grammarAccess.getListActivityAccess().getNameAssignment_1(), "rule__ListActivity__NameAssignment_1");
					put(grammarAccess.getListActivityAccess().getDataSourceAssignment_4(), "rule__ListActivity__DataSourceAssignment_4");
					put(grammarAccess.getListActivityAccess().getLayoutAssignment_5_1(), "rule__ListActivity__LayoutAssignment_5_1");
					put(grammarAccess.getListActivityAccess().getItemLayoutAssignment_7(), "rule__ListActivity__ItemLayoutAssignment_7");
					put(grammarAccess.getListActivityAccess().getActionsAssignment_8(), "rule__ListActivity__ActionsAssignment_8");
					put(grammarAccess.getTabActivityAccess().getNameAssignment_1(), "rule__TabActivity__NameAssignment_1");
					put(grammarAccess.getTabActivityAccess().getTabsAssignment_3(), "rule__TabActivity__TabsAssignment_3");
					put(grammarAccess.getTabAccess().getActivityAssignment_1(), "rule__Tab__ActivityAssignment_1");
					put(grammarAccess.getGenericActionAccess().getNameAssignment_1(), "rule__GenericAction__NameAssignment_1");
					put(grammarAccess.getGoToURLActionAccess().getUrlAssignment_1(), "rule__GoToURLAction__UrlAssignment_1");
					put(grammarAccess.getShowLayoutActionAccess().getLayoutAssignment_1(), "rule__ShowLayoutAction__LayoutAssignment_1");
					put(grammarAccess.getInvokeActivityActionAccess().getActivityAssignment_1(), "rule__InvokeActivityAction__ActivityAssignment_1");
					put(grammarAccess.getLoadResourceActionAccess().getResourceAssignment_1(), "rule__LoadResourceAction__ResourceAssignment_1");
					put(grammarAccess.getLoadResourceActionAccess().getToVarAssignment_2_1(), "rule__LoadResourceAction__ToVarAssignment_2_1");
					put(grammarAccess.getLoadResourceActionAccess().getAfterLoadAssignment_3_1(), "rule__LoadResourceAction__AfterLoadAssignment_3_1");
					put(grammarAccess.getStringPropertyValueAccess().getValueAssignment_0(), "rule__StringPropertyValue__ValueAssignment_0");
					put(grammarAccess.getStringPropertyValueAccess().getResourceAssignment_1_0(), "rule__StringPropertyValue__ResourceAssignment_1_0");
					put(grammarAccess.getStringPropertyValueAccess().getExternalResourceAssignment_1_1_1(), "rule__StringPropertyValue__ExternalResourceAssignment_1_1_1");
					put(grammarAccess.getIntegerPropertyValueAccess().getValueAssignment_0(), "rule__IntegerPropertyValue__ValueAssignment_0");
					put(grammarAccess.getIntegerPropertyValueAccess().getResourceAssignment_1_0(), "rule__IntegerPropertyValue__ResourceAssignment_1_0");
					put(grammarAccess.getIntegerPropertyValueAccess().getExternalResourceAssignment_1_1_1(), "rule__IntegerPropertyValue__ExternalResourceAssignment_1_1_1");
					put(grammarAccess.getBooleanPropertyValueAccess().getValueAssignment_0(), "rule__BooleanPropertyValue__ValueAssignment_0");
					put(grammarAccess.getBooleanPropertyValueAccess().getResourceAssignment_1_0(), "rule__BooleanPropertyValue__ResourceAssignment_1_0");
					put(grammarAccess.getBooleanPropertyValueAccess().getExternalResourceAssignment_1_1_1(), "rule__BooleanPropertyValue__ExternalResourceAssignment_1_1_1");
					put(grammarAccess.getColorPropertyValueAccess().getValueAssignment_0(), "rule__ColorPropertyValue__ValueAssignment_0");
					put(grammarAccess.getColorPropertyValueAccess().getResourceAssignment_1_0(), "rule__ColorPropertyValue__ResourceAssignment_1_0");
					put(grammarAccess.getColorPropertyValueAccess().getExternalResourceAssignment_1_1_1(), "rule__ColorPropertyValue__ExternalResourceAssignment_1_1_1");
					put(grammarAccess.getDimensionPropertyValueAccess().getValueAssignment_0(), "rule__DimensionPropertyValue__ValueAssignment_0");
					put(grammarAccess.getDimensionPropertyValueAccess().getResourceAssignment_1_0(), "rule__DimensionPropertyValue__ResourceAssignment_1_0");
					put(grammarAccess.getDimensionPropertyValueAccess().getExternalResourceAssignment_1_1_1(), "rule__DimensionPropertyValue__ExternalResourceAssignment_1_1_1");
					put(grammarAccess.getDrawableResourcePropertyValueAccess().getValueAssignment_0(), "rule__DrawableResourcePropertyValue__ValueAssignment_0");
					put(grammarAccess.getDrawableResourcePropertyValueAccess().getResourceAssignment_1_0(), "rule__DrawableResourcePropertyValue__ResourceAssignment_1_0");
					put(grammarAccess.getDrawableResourcePropertyValueAccess().getExternalResourceAssignment_1_1_1(), "rule__DrawableResourcePropertyValue__ExternalResourceAssignment_1_1_1");
					put(grammarAccess.getDrawableImageResourcePropertyValueAccess().getResourceAssignment_0(), "rule__DrawableImageResourcePropertyValue__ResourceAssignment_0");
					put(grammarAccess.getDrawableImageResourcePropertyValueAccess().getExternalResourceAssignment_1_1(), "rule__DrawableImageResourcePropertyValue__ExternalResourceAssignment_1_1");
					put(grammarAccess.getGenericWidgetAccess().getUnorderedGroup_4(), "rule__GenericWidget__UnorderedGroup_4");
					put(grammarAccess.getTextViewAccess().getUnorderedGroup_4(), "rule__TextView__UnorderedGroup_4");
					put(grammarAccess.getButtonAccess().getUnorderedGroup_4(), "rule__Button__UnorderedGroup_4");
					put(grammarAccess.getImageButtonAccess().getUnorderedGroup_4(), "rule__ImageButton__UnorderedGroup_4");
					put(grammarAccess.getLinkAccess().getUnorderedGroup_4(), "rule__Link__UnorderedGroup_4");
					put(grammarAccess.getSpinnerAccess().getUnorderedGroup_3(), "rule__Spinner__UnorderedGroup_3");
					put(grammarAccess.getEditTextAccess().getUnorderedGroup_4(), "rule__EditText__UnorderedGroup_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.amalgam.tutorials.xtext.ui.contentassist.antlr.internal.InternalDroidParser typedParser = (org.eclipse.amalgam.tutorials.xtext.ui.contentassist.antlr.internal.InternalDroidParser) parser;
			typedParser.entryRuleApplication();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DroidGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DroidGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
