
/*
 * generated by Xtext
 */
 
package org.eclipse.amalgam.tutorials.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class DroidExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.amalgam.tutorials.xtext.ui.internal.DroidActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.amalgam.tutorials.xtext.ui.internal.DroidActivator.getInstance().getInjector("org.eclipse.amalgam.tutorials.xtext.Droid");
	}
	
}
